// Mocks generated by Mockito 5.3.2 from annotations
// in flutter_clean/test/features/number_trivia/domain/use_cases/get_number_trivia_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:flutter_clean/features/number_trivia/domain/entities/number_trivia.dart'
    as _i2;
import 'package:flutter_clean/features/number_trivia/domain/repositories/number_trivia_repository.dart'
    as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeNumberTrivia_0 extends _i1.SmartFake implements _i2.NumberTrivia {
  _FakeNumberTrivia_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [NumberTriviaRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockNumberTriviaRepository extends _i1.Mock
    implements _i3.NumberTriviaRepository {
  @override
  _i4.Future<_i2.NumberTrivia> getNumberTrivia(int? number) =>
      (super.noSuchMethod(
        Invocation.method(
          #getNumberTrivia,
          [number],
        ),
        returnValue: _i4.Future<_i2.NumberTrivia>.value(_FakeNumberTrivia_0(
          this,
          Invocation.method(
            #getNumberTrivia,
            [number],
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i2.NumberTrivia>.value(_FakeNumberTrivia_0(
          this,
          Invocation.method(
            #getNumberTrivia,
            [number],
          ),
        )),
      ) as _i4.Future<_i2.NumberTrivia>);
  @override
  _i4.Future<_i2.NumberTrivia> getRandomNumberTrivia() => (super.noSuchMethod(
        Invocation.method(
          #getRandomNumberTrivia,
          [],
        ),
        returnValue: _i4.Future<_i2.NumberTrivia>.value(_FakeNumberTrivia_0(
          this,
          Invocation.method(
            #getRandomNumberTrivia,
            [],
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i2.NumberTrivia>.value(_FakeNumberTrivia_0(
          this,
          Invocation.method(
            #getRandomNumberTrivia,
            [],
          ),
        )),
      ) as _i4.Future<_i2.NumberTrivia>);
}
